# Generated by Django 3.0.1 on 2020-01-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_heading',
            field=models.CharField(default='', max_length=200),
        ),
    ]
