# Generated by Django 2.2.9 on 2020-02-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sub_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_heading',
        ),
    ]
